### PR TITLE
Added ability to process file in chunks Fixes #2

### LINKED ISSUE #2: Reading file in chunks rather than in its entirety
## The Problem

Currently, to calculate the checksum of a file, the entire file must be loaded into the memory. This is inefficient and impractical for large files.

## Possible Solutions

The most viable solution to this issue is the read the file in chunks and calculate the checksum at each step. At the end of the file, the checksum is still the same as what it would be if you had calculated with the entire file in memory.

It's best to implement another function to read a file and pass that into the calculation functions so code reusability is increased.

## Testing

To test that the function works properly, test the checksum of the old and new functions for the same file. If they match, the code works fine.

---
 - Block time: 40 mins (You need to give updates every 40 mins if you have been assigned)
 - Bounty points: 60

### PR DESCRIPTION
**Pull request by abhiraj2**
Added ability to to calculate hashes in chunks, fixes #2 
Also fixed existing issues with MD5 and SHA1 (Read instruction had bugs)
Added a timer for calculating the amount of time elapsed

### CODE REVIEW

**Comment by abhiraj2** [comment]
@PhoenixFlame101 have you checked this out, Ik the competition is over but just worked on this so thought I will make a PR

**Comment by PhoenixFlame101** [comment]
I actually had tested it, just forgot to reply. My bad :sweat_smile:.

The reason I haven't approved it is because the calculation of the checksums still takes a very long time, possibly because of the small buffer size. (Try using something like 10-100 MB).

Calculating the checksum for a 425 MB file takes over 30 seconds, whereas `sha256sum` takes 3.

**Comment by abhiraj2** [comment]
Changed the block size
Checked for 1GB file, 

The original sha256 function takes around 107 seconds
going chunk by chunk reduces it to around 96 seconds

image

**Comment by abhiraj2** [comment]
@PhoenixFlame101 take a look now

**Comment by PhoenixFlame101** [comment]
I'm getting good times on the release build of `quickhash`! A 1 GB file takes only about 5s on SHA-256.

One small thing though, you have duplicated imports in `algorithm.rs` that results in a compile error.

**Comment by abhiraj2** [comment]
weirdly didn't give me any errors, but fixed it now, so take a look @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
Thanks!

**Pull request merged**
