### PR TITLE
Added SHA-1 Algorithm Fixes #1

### LINKED ISSUE #1: Lack of SHA-1 support
## The Problem

quickhash doesn't have support for SHA-1 algorithm, any PR that might close this issue should implement these algorithms the same way SHA-256 and MD5 are implemented. While it is cryptographically broken, it is still useful for legacy interoperability purposes.

## Possible Solutions

There's a crate `sha1` contains the SHA-1 alg already implemented. Solving this issue requires you to use this crate and add SHA-1 to the menu.  Make sure the algorithm function is in `algorithm.rs`

## Expected output

If you want to confirm that the algorithm works correctly, you can check against this checksum:

    cargo run NOTICE
    The expected SHA-1 output should be: 2cdae58602dd8b1734bfd2c462dee6497ac28872

---
 - Block time: 30 mins (You need to give updates every 30 mins if you have been assigned)
 - Bounty points: 30

### PR DESCRIPTION
**Pull request by abhiraj2**
Added code that enables support for sha-1 algorithm Fixes #1

### CODE REVIEW

**Comment by abhiraj2** [comment]
@PhoenixFlame101 please take a look

**Comment by abhiraj2** [comment]
any update @PhoenixFlame101?

**Comment by PhoenixFlame101** [comment]
SHA-256 throws an exception, and MD5 and SHA-1 are both returning nothing

**Comment by abhiraj2** [comment]
Fixed the issues. Check once more @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
Functions work fine, so that's good! Here's some remaining issues that need to be cleared up:

 - Warn from cargo on line 55
 - Remove the checksum file from the commit

**Comment by abhiraj2** [comment]
made the changes, @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
Good job!

**Comment by PhoenixFlame101** [comment]
!bounty 30

**Pull request merged**
