### PR TITLE
Created flags for checksum-file and create-checksum file. Fixes #4

### LINKED ISSUE #4: Creating and verifying a checksum file in a directory
## The Problem

Add support to verify from and create checksum files.

## Possible Solutions

A checksum file is a plaintext file containing the checksums of all the files in a directory followed by the file name.

    Checksum format:
    2012b030c3f01589c399da291c57d803  NOTICE (notice the 2 spaces between the checksum and filename)

This feature should be triggered by passing in a CLI option `--create-checksum-file`. The program should calculate checksums for all the files in the root of the current working directory, and save it in a file `<algorithm>.checksum`. For example, an SHA-256 checksum will have the filename `sha256.checksum`.

There should also be support for the CLI option `--checksum-file` followed by a filepath, pointing to the checksum file for that directory. The algorithm should be automatically determined from the filename and all the filenames should be printed followed by a pass/fail result.

Examples:

    $ cargo run --create-checksum-file
    The file <alg>.checksum is located at <filepath>

    $ cargo run --checksum-file sha256.checksum
    NOTICE - Passed
    LICENSE - Passed
    README.md - Failed

## Testing

You can test the functionality by creating and validating the files using both functions. To create fail conditions on purpose, you can simply edit the file and see if it fails.

---
 - Block time: 45 mins (You need to give updates every 45 mins if you have been assigned)
 - Bounty points: 80

### PR DESCRIPTION
**Pull request by abhiraj2**
Added code that creates and enables user to perform directory wide checksum validation using create-checksum-file and checksum-file

`cargo run create-checksum-file`: Makes the <algo>.checksum file
`cargo run checksum-file` Does validation for all the FILES (skips dirs) present in the root directory

Fixes #4

### CODE REVIEW

**Comment by PhoenixFlame101** [comment]
Great job so far! Here are some issues that need fixing:

 - While vaildating the files, the checksum file is also checked, and as a result, always fails. You can skip the checksum files during validation.
 - The format mentioned in the issue is not followed. Your checksum file does not contain filenames and relies on alphabetical order being maintained, add the file names and verify against the filenames in the file only.

**Comment by abhiraj2** [comment]
Alright working on it @PhoenixFlame101

**Comment by abhiraj2** [comment]
I have made the changes, please check now @PhoenixFlame101

**Comment by abhiraj2** [comment]
any update? @PhoenixFlame101

**Comment by PhoenixFlame101** [comment]
lgtm 👍

**Comment by PhoenixFlame101** [comment]
!bounty 80

**Comment by NavinShrinivas** [comment]
!bounty 70

**Pull request merged**
